create table if not exists public.products (
 id bigint generated by default as identity primary key,
 name text not null,
 category text,
 supplier_price numeric(10,2) not null check (supplier_price >= 0),
 selling_price numeric(10,2) not null check (selling_price >= 0),
 image_emoji text default '🛍️',
 rating numeric(2,1),
 active boolean default true,
 created_at timestamptz default now()
);

create table if not exists public.orders (
 id bigint generated by default as identity primary key,
 customer_name text not null,
 phone text not null,
 address text not null,
 total numeric(10,2) not null,
 status text default 'pending',
 created_at timestamptz default now()
);

create table if not exists public.order_items (
 id bigint generated by default as identity primary key,
 order_id bigint references public.orders(id) on delete cascade,
 product_id bigint references public.products(id),
 quantity integer not null default 1,
 selling_price numeric(10,2) not null
);

alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- Public storefront can read active products.
create policy "public can read active products" on public.products
for select to anon using (active = true);

insert into public.products(name,category,supplier_price,selling_price,image_emoji,rating)
values
('Wireless Earbuds Pro','electronics',499,699,'🎧',4.6),
('Smart Watch Series','electronics',799,1099,'⌚',4.5),
('LED Desk Lamp','home',299,449,'💡',4.7),
('Magnetic Mobile Stand','mobile',149,249,'📱',4.3);
